.catalog:
  name: "Registry"
  version: "v2.4.1"
  description: "Docker Registry"
  uuid: registry-2.4
  questions: 
    - variable: "HOST_LABEL"
      label: "Host label"
      description: "Host label where to run Registry service"
      required: true
      type: "string"
      default: "registry_host=true"
    - variable: "DOMAIN"
      label: "FQDN"
      description: "FQDN of server. This should be the CN in the certificates and will be the URL to contact the Registry and Web interface"
      required: true
      type: "string"
    - variable: "KEYPATH"
      label: "Path of local folder for ssh key"
      description: "path of ssh key in local host"
      required: true
      type: "string"
    - variable: "RPORT"
      label: "Registry Port"
      description: "Port on which to run the registry service"
      default: 5000
      required: true
      type: "int"
    - variable: "PPORT"
      label: "Admin Port"
      description: "Port on which to run the SSL Portus administration service and API"
      default: 443
      required: true
      type: "int"
    - variable: "DRIVER"
      label: "Storage Pool"
      description: "Convoy storage pool name"
      required: true
      type: "string"
      default: "convoy"
    - variable: "PFX"
      label: "Convoy volume prefix"
      description: "Prefix to use for all Convoy storage pool volumes"
      required: true
      type: "string"
      default: "registry"

registry:
  scale: 1
