db:
  image: mariadb:10
  environment:
    MYSQL_DATABASE: portus
    MYSQL_PASSWORD: ${DBPASSWORD}
    MYSQL_ROOT_PASSWORD: ${ROOTPASSWORD}
    MYSQL_USER: portus
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
    fxnbd.portus.db: 1
  tty: true
  net: host
  volumes:
  - ${PFX}-db:/var/lib/mysql
  stdin_open: true
  volume_driver: ${DRIVER}

portus:
  environment:
    MARIADB_ADAPTER: mysql2
    MARIADB_ENCODING: utf8
    MARIADB_HOST: ${DOMAIN}
    MARIADB_PORT: 3306
    MARIADB_USER: portus
    MARIADB_PASSWORD: ${DBPASSWORD}
    MARIADB_DATABASE: portus
    RACK_ENV: production
    RAILS_ENV: production
    PUMA_SSL_KEY: /certs/server-key.pem
    PUMA_SSL_CRT: /certs/server-crt.pem
    PUMA_IP: ${DOMAIN}
    PUMA_PORT: ${PPORT}
    PUMA_WORKERS: 4
    PORTUS_MACHINE_FQDN: ${DOMAIN}
    PORTUS_DELETE_ENABLED: true
    PORTUS_SECRET_KEY_BASE: d38a16b9
    PORTUS_ENCRYPTION_PRIVATE_KEY_PATH: /certs/server-key.pem
    PORTUS_PORTUS_PASSWORD: foxconnbd
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: ${HOST_LABEL}
    io.rancher.scheduler.affinity:container_label_soft: fxnbd.portus.db=1
    fxnbd.portus.web: 1
  tty: true
  net: host
  volumes:
  - ${KEYPATH}:/certs
  image: mattwang201301/portus:2.0.5
  stdin_open: true
